{% set name = "param-sweeps" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 85d02e16060955ed87eb5427781a45251468ad2d04dd6f2fef5bb532b93ca0f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy 1.26.*
    - geoh5py 0.10.*

test:
  imports:
    - param_sweeps
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'A Parameter sweeper for applications driven by ui.json files.'
  description: |
    The param-sweeps library contains two main modules. One is for generating sweep files, 
    and the other is to run a sweep over some number of parameters in a driver application.
  license: MIT
  license_file:
    - LICENSE
  dev_url: https://github.com/MiraGeoscience/param-sweeps

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
